# Generated by Django 5.0.6 on 2024-06-29 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(error_messages='Coloca algo valido', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(error_messages='Coloca algo valido', max_length=50)),
                ('stock', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Aplicacion.tipoproducto')),
            ],
        ),
    ]
