# Generated by Django 5.0.6 on 2024-06-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0004_remove_pedido_cantidad_remove_pedido_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoproducto',
            name='estado',
            field=models.CharField(choices=[('Cancelado', 'Cancelado'), ('En circulacion', 'En circulacion'), ('Entregado', 'Entregado')], default='Sin asignar', max_length=50),
        ),
    ]
