# Generated by Django 5.0.6 on 2024-06-29 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('rut', models.CharField(error_messages='Coloca algo valido', max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(error_messages='Coloca algo valido', max_length=50)),
                ('apellido', models.CharField(error_messages='Coloca algo valido', max_length=50)),
                ('correo', models.EmailField(error_messages='Coloca algo valido', max_length=254)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Aplicacion.comuna')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Aplicacion.region'),
        ),
    ]
