# Generated by Django 5.0.6 on 2024-06-30 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0002_tipoproducto_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='Aplicacion/media/productos'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Aplicacion.persona')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Aplicacion.producto')),
            ],
        ),
    ]
