# Generated by Django 5.0.6 on 2024-06-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0006_alter_pedidoproducto_estado_alter_region_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comuna',
            name='region',
            field=models.CharField(choices=[('II', 'Antofagasta'), ('XV', 'Arica y Parinacota'), ('III', 'Atacama'), ('XI', 'Aysén'), ('VIII', 'Biobío'), ('IV', 'Coquimbo'), ('IX', 'La Araucanía'), ('X', 'Los Lagos'), ('XIV', 'Los Ríos'), ('XII', 'Magallanes'), ('VII', 'Maule'), ('XIII', 'Metropolitana'), ('VI', "O'Higgins"), ('I', 'Tarapacá'), ('V', 'Valparaíso'), ('XVI', 'Ñuble')], default='Pagado', max_length=50),
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
