REGIONES_CHILE = {
    ("I", "Tarapacá"),
    ("II", "Antofagasta"),
    ("III", "Atacama"),
    ("IV", "Coquimbo"),
    ("V", "Valparaíso"),
    ("VI", "O'Higgins"),
    ("VII", "Maule"),
    ("VIII", "Biobío"),
    ("IX", "La Araucanía"),
    ("X", "Los Lagos"),
    ("XI", "Aysén"),
    ("XII", "Magallanes"),
    ("XIII", "Metropolitana"),
    ("XIV", "Los Ríos"),
    ("XV", "Arica y Parinacota"),
    ("XVI", "Ñuble")
}

COMUNAS_TARAPACA = {
    ("IQUIQUE", "Iquique"),
    ("ALTO_HOSPICIO", "Alto Hospicio"),
    ("POZO_ALMONTE", "Pozo Almonte"),
    ("CAMIÑA", "Camiña"),
    ("COLCHANE", "Colchane"),
    ("HUARA", "Huara"),
    ("PICA", "Pica")
}

COMUNAS_ANTOFAGASTA = {
    ("ANTOFAGASTA", "Antofagasta"),
    ("MEJILLONES", "Mejillones"),
    ("SIERRA_GORDA", "Sierra Gorda"),
    ("TALTAL", "Taltal"),
    ("CALAMA", "Calama"),
    ("OLLAGÜE", "Ollagüe"),
    ("SAN_PEDRO_DE_ATACAMA", "San Pedro de Atacama"),
    ("TOCOPILLA", "Tocopilla"),
    ("MARÍA_ELENA", "María Elena")
}

COMUNAS_ATACAMA = {
    ("COPIAPÓ", "Copiapó"),
    ("CALDERA", "Caldera"),
    ("TIERRA_AMARILLA", "Tierra Amarilla"),
    ("CHAÑARAL", "Chañaral"),
    ("DIEGO_DE_ALMAGRO", "Diego de Almagro"),
    ("VALLENAR", "Vallenar"),
    ("ALTO_DEL_CARMEN", "Alto del Carmen"),
    ("FREIRINA", "Freirina"),
    ("HUASCO", "Huasco")
}

COMUNAS_COQUIMBO = {
    ("COQUIMBO", "Coquimbo"),
    ("LA_SERENA", "La Serena"),
    ("ANDACOLLO", "Andacollo"),
    ("LA_HIGUERA", "La Higuera"),
    ("PAIGUANO", "Paiguano"),
    ("VICUÑA", "Vicuña"),
    ("ILLAPEL", "Illapel"),
    ("CANELA", "Canela"),
    ("LOS_VILLOS", "Los Vilos"),
    ("SALAMANCA", "Salamanca"),
    ("OVALLE", "Ovalle"),
    ("COMBARBALÁ", "Combarbalá"),
    ("MONTE_PATRIA", "Monte Patria"),
    ("PUNITAQUI", "Punitaqui"),
    ("RÍO_HURTADO", "Río Hurtado")
}

COMUNAS_VALPARAISO = {
    ("VALPARAÍSO", "Valparaíso"),
    ("CASABLANCA", "Casablanca"),
    ("CONCÓN", "Concón"),
    ("JUAN_FERNÁNDEZ", "Juan Fernández"),
    ("PUCHUNCAVÍ", "Puchuncaví"),
    ("QUINTERO", "Quintero"),
    ("VIÑA_DEL_MAR", "Viña del Mar"),
    ("ISLA_DE_PASCUA", "Isla de Pascua"),
    ("LOS_ANDÉS", "Los Andes"),
    ("CALLE_LARGA", "Calle Larga"),
    ("RINCONADA", "Rinconada"),
    ("SAN_ESTEBAN", "San Esteban"),
    ("LA_LIGUA", "La Ligua"),
    ("CABILDO", "Cabrero"),
    ("PAPUDO", "Papudo"),
    ("PETORCA", "Petorca"),
    ("ZAPALLAR", "Zapallar"),
    ("QUILLOTA", "Quillota"),
    ("CALERA", "Calera"),
    ("HIJUELAS", "Hijuelas"),
    ("LA_CRUZ", "La Cruz"),
    ("NORQUIM", "Nogales"),
    ("LIMACHE", "Limache"),
    ("OLMUÉ", "Olmué"),
    ("QUILPUE", "Quilpué"),
    ("VILLA_ALEMANA", "Villa Alemana"),
    ("VALLA_QUILOTA", "Valle Quilota"),
    ("ALGARROBO", "Algarrobo"),
    ("CARTAGENA", "Cartagena"),
    ("EL_QUISCO", "El Quisco"),
    ("EL_TABO", "El Tabo"),
    ("SANTO_DOMINGO", "Santo Domingo")
}

COMUNAS_METROPOLITANA = {
    ("SANTIAGO", "Santiago"),
    ("CERRILLOS", "Cerrillos"),
    ("CERRO_NAVIA", "Cerro Navia"),
    ("CONCHALÍ", "Conchalí"),
    ("EL_BOSQUE", "El Bosque"),
    ("ESTACIÓN_CENTRAL", "Estación Central"),
    ("HUECHURABA", "Huechuraba"),
    ("INDEPENDENCIA", "Independencia"),
    ("LA_CISTERNA", "La Cisterna"),
    ("LA_FLORIDA", "La Florida"),
    ("LA_GRANJA", "La Granja"),
    ("LA_PINTANA", "La Pintana"),
    ("LA_REINA", "La Reina"),
    ("LAS_CONDES", "Las Condes"),
    ("LO_BARNECHEA", "Lo Barnechea"),
    ("LO_ESPEJO", "Lo Espejo"),
    ("LO_PRADO", "Lo Prado"),
    ("MACUL", "Macul"),
    ("MAIPÚ", "Maipú"),
    ("ÑUÑOA", "Ñuñoa"),
    ("PADRE_HURTADO", "Padre Hurtado"),
    ("PEDRO_AGUIRRE_CERDA", "Pedro Aguirre Cerda"),
    ("PEÑALOLÉN", "Peñalolén"),
    ("PUDAHUEL", "Pudahuel"),
    ("QUILICURA", "Quilicura"),
    ("QUINTA_NORMAL", "Quinta Normal"),
    ("RECOLETA", "Recoleta"),
    ("RENCA", "Renca"),
    ("SAN_BERNARDO", "San Bernardo"),
    ("SAN_JOAQUÍN", "San Joaquín"),
    ("SAN_JOSÉ_DE_MAIPÚ", "San José de Maipú"),
    ("SAN_MIGUEL", "San Miguel"),
    ("SAN_RAMÓN", "San Ramón"),
    ("VITACURA", "Vitacura"),
    ("PUENTE_ALTO", "Puente Alto"),
    ("PIRQUE", "Pirque"),
    ("SAN_JOSE_DE_MAIPO", "San José de Maipo"),
    ("CALERA_DE_TANGO", "Calera de Tango"),
    ("COLINA", "Colina"),
    ("LAMPA", "Lampa"),
    ("TILTIL", "Tiltil")
}

COMUNAS_OHIGGINS = {
    ("RANCAGUA", "Rancagua"),
    ("CODEGUA", "Codegua"),
    ("COINCO", "Coinco"),
    ("COLTAUCO", "Coltauco"),
    ("DOÑIHUE", "Doñihue"),
    ("GRANEROS", "Graneros"),
    ("LAS_CABRAS", "Las Cabras"),
    ("MACHALÍ", "Machalí"),
    ("MALLOA", "Malloa"),
    ("MOSTAZAL", "Mostazal"),
    ("OLIVAR", "Olivar"),
    ("PEUMO", "Peumo"),
    ("PICHIDEGUA", "Pichidegua"),
    ("QUINTA_DE_TILCOCO", "Quinta de Tilcoco"),
    ("RENGO", "Rengo"),
    ("REQUÍNOA", "Requínoa"),
    ("SAN_FERNANDO", "San Fernando"),
    ("SAN_VICENTE_DE_TAGUA_TAGUA", "San Vicente de Tagua Tagua"),
    ("PUMANQUE", "Pumanque"),
    ("SANTA_CRUZ", "Santa Cruz")
}

COMUNAS_MAULE = {
    ("TALCA", "Talca"),
    ("CONSTITUCIÓN", "Constitución"),
    ("CUREPTO", "Curepto"),
    ("EMPEDRADO", "Empedrado"),
    ("MAULE", "Maule"),
    ("PELARCO", "Pelarco"),
    ("PENCAHUE", "Pencahue"),
    ("RÍO_CLARO", "Río Claro"),
    ("SAN_CLEMENTE", "San Clemente"),
    ("SAN_RAFAEL", "San Rafael"),
    ("CAUQUENES", "Cauquenes"),
    ("CHANCO", "Chanco"),
    ("PELLUHUE", "Pelluhue"),
    ("CURICÓ", "Curicó"),
    ("HUALAÑÉ", "Hualañé"),
    ("LICANTÉN", "Licantén"),
    ("MOLINA", "Molina"),
    ("RAUCO", "Rauco"),
    ("ROMERAL", "Romeral"),
    ("SAGRADA_FAMILIA", "Sagrada Familia"),
    ("TENO", "Teno"),
    ("VICHUQUÉN", "Vichuquén")
}

COMUNAS_BIOBIO = {
    ("CONCEPCIÓN", "Concepción"),
    ("CORONEL", "Coronel"),
    ("CHIGUAYANTE", "Chiguayante"),
    ("FLORIDA", "Florida"),
    ("HUALQUI", "Hualqui"),
    ("LOTA", "Lota"),
    ("PENCO", "Penco"),
    ("SAN_PEDRO_DE_LA_PAZ", "San Pedro de la Paz"),
    ("SANTA_JUANA", "Santa Juana"),
    ("TALCAHUANO", "Talcahuano"),
    ("TOMÉ", "Tomé"),
    ("HUALPÉN", "Hualpén"),
    ("LEBU", "Lebu"),
    ("ARAUCO", "Arauco"),
    ("CAÑETE", "Cañete"),
    ("CONTULMO", "Contulmo"),
    ("CURANILAHUE", "Curanilahue"),
    ("LONCOCHE", "Lanquil"),
    ("LOS_ÁLAMOS", "Los Álamos"),
    ("TIRÚA", "Tirúa"),
    ("ALTO_BIOBÍO", "Alto Biobío"),
    ("ANTUCO", "Antuco"),
    ("CABRERO", "Cabrero"),
    ("LAJA", "Laja"),
    ("LOS_ÁNGELES", "Los Ángeles"),
    ("MULCHÉN", "Mulchén"),
    ("NACIMIENTO", "Nacimiento"),
    ("NEGRETE", "Negrete"),
    ("QUILACO", "Quilaco"),
    ("QUILLECO", "Quilleco"),
    ("SAN_ROSENDO", "San Rosendo"),
    ("SANTA_BÁRBARA", "Santa Bárbara"),
    ("TUCAPEL", "Tucapel"),
    ("YUMBEL", "Yumbel")
}

COMUNAS_ARAUCANIA = {
    ("TEMUCO", "Temuco"),
    ("CARAHUE", "Carahue"),
    ("CUNCO", "Cunco"),
    ("CURARREHUE", "Curarrehue"),
    ("FREIRE", "Freire"),
    ("GALVARINO", "Galvarino"),
    ("GORBEA", "Gorbea"),
    ("LAUTARO", "Lautaro"),
    ("LONCOCHE", "Loncoche"),
    ("MELIPEUCO", "Melipeuco"),
    ("NUEVA_IMPERIAL", "Nueva Imperial"),
    ("PADRE_LAS_CASAS", "Padre Las Casas"),
    ("PERQUENCO", "Perquenco"),
    ("PITRUFQUÉN", "Pitrufquén"),
    ("PUCÓN", "Pucón"),
    ("SAÚL_DE_LA_MAZA", "Saúl de la Maza"),
    ("TEMUCO", "Temuco"),
    ("TEODORO_SCHMIDT", "Teodoro Schmidt"),
    ("TOLTÉN", "Toltén"),
    ("VILCÚN", "Vilcún"),
    ("VILLARRICA", "Villarrica"),
    ("CHOLCHOL", "Cholchol")
}

COMUNAS_LOS_LAGOS = {
    ("PUERTO_MONTT", "Puerto Montt"),
    ("CALBUCO", "Calbuco"),
    ("COCHAMÓ", "Cochamó"),
    ("MAULLÍN", "Maullín"),
    ("PUERTO_VARAS", "Puerto Varas"),
    ("FRESIA", "Fresia"),
    ("FRUTILLAR", "Frutillar"),
    ("LLANQUIHUE", "Llanquihue"),
    ("LOS_MUERMOS", "Los Muermos"),
    ("PUERTO_OCTAY", "Puerto Octay"),
    ("PURRANQUE", "Purranque"),
    ("PUYEHUE", "Puyehue"),
    ("RÍO_NEGRO", "Río Negro"),
    ("SAN_PABLO", "San Pablo"),
    ("OSORNO", "Osorno"),
    ("PUERTO_OCTAY", "Puerto Octay"),
    ("PURRANQUE", "Purranque"),
    ("PUYEHUE", "Puyehue"),
    ("RÍO_NEGRO", "Río Negro"),
    ("SAN_PABLO", "San Pablo"),
    ("SAN_JUAN_DE_LA_COSTA", "San Juan de la Costa"),
    ("PUERTO_VARAS", "Puerto Varas"),
    ("FRESIA", "Fresia"),
    ("FRUTILLAR", "Frutillar"),
    ("LLANQUIHUE", "Llanquihue"),
    ("LOS_MUERMOS", "Los Muermos"),
    ("PUERTO_OCTAY", "Puerto Octay"),
    ("PURRANQUE", "Purranque"),
    ("PUYEHUE", "Puyehue"),
    ("RÍO_NEGRO", "Río Negro"),
    ("SAN_PABLO", "San Pablo"),
    ("SAN_JUAN_DE_LA_COSTA", "San Juan de la Costa")
}

COMUNAS_AYSEN = {
    ("COYHAIQUE", "Coyhaique"),
    ("LAGO_VERDE", "Lago Verde"),
    ("AYSÉN", "Aysén"),
    ("CISNES", "Cisnes"),
    ("GUAITECAS", "Guaitecas"),
    ("CHILE_CHICO", "Chile Chico"),
    ("RÍO_IBÁÑEZ", "Río Ibáñez")
}

COMUNAS_MAGALLANES = {
    ("PUNTA_ARENAS", "Punta Arenas"),
    ("LAGUNA_BLANCA", "Laguna Blanca"),
    ("RÍO_VERDE", "Río Verde"),
    ("SAN_GREGORIO", "San Gregorio"),
    ("CABO_DE_HORNOS", "Cabo de Hornos"),
    ("ANTÁRTICA", "Antártica"),
    ("PORVENIR", "Porvenir"),
    ("PRIMAVERA", "Primavera"),
    ("TIMAUKEL", "Timaukel"),
    ("NATALES", "Natales"),
    ("TORRES_DEL_PAINE", "Torres del Paine")
}

COMUNAS_LOS_RIOS = {
    ("VALDIVIA", "Valdivia"),
    ("CORRAL", "Corral"),
    ("LANCO", "Lanco"),
    ("LOS_LAGOS", "Los Lagos"),
    ("MÁFIL", "Máfil"),
    ("MARIQUINA", "Mariquina"),
    ("PAILLACO", "Paillaco"),
    ("PANGUIPULLI", "Panguipulli"),
    ("LA_UNIÓN", "La Unión"),
    ("FUTRONO", "Futrono"),
    ("RÍO_BUENO", "Río Bueno")
}

COMUNAS_ARICA = {
    ("ARICA", "Arica"),
    ("CAMARONES", "Camarones"),
    ("GENERAL_LAGOS", "General Lagos"),
    ("PUTRE", "Putre")
}

COMUNAS_NUBLE = {
    ("CHILLÁN", "Chillán"),
    ("BULNES", "Bulnes"),
    ("COBQUECURA", "Cobquecura"),
    ("COELEMU", "Coelemu"),
    ("COIHUECO", "Coihueco"),
    ("CHILLÁN_VIEJO", "Chillán Viejo"),
    ("EL_CARMEN", "El Carmen"),
    ("NINHUE", "Ninhue"),
    ("ÑIQUÉN", "Ñiquén"),
    ("PEMUCO", "Pemuco"),
    ("PINTO", "Pinto"),
    ("PORTEZUELO", "Portezuelo"),
    ("QUILLÓN", "Quillón"),
    ("QUIRIHUE", "Quirihue"),
    ("RÁNQUIL", "Ránquil"),
    ("SAN_CARLOS", "San Carlos"),
    ("SAN_FABIÁN", "San Fabián"),
    ("SAN_NICOLÁS", "San Nicolás"),
    ("TREGUACO", "Treguaco"),
    ("YUNGAY", "Yungay")
}
